spring:
    application.name: eureka-application

configurationServer:
    port: 9000

server:
    port: ${configurationServer.port}

eureka:
    client:
        fetchRegistry: false
        registerWithEureka: false
        enabled: true
        instance-info-replication-interval-seconds: 10
        registry-fetch-interval-seconds: 10
    dashboard:
        path: /registry
    instance:
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10